In [2]:
import pandas as pd

In [3]:
data = pd.read_excel('supplychain.xlsx')

In [4]:
data.head()

,Source,Destination,Container Size,Carrier,Travel Mode,Fixed Freight Cost,Port/Airport/Rail Handling Cost,Bunker/ Fuel Cost,Documentation Cost,Equipment Cost,...,CustomClearance time (hours),Port/Airport/Rail Handling time (hours),Transit time (hours),Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday
0,Singapore Port,Shanghai Port,67,COSCO,Sea,300,300,400,180,20,...,24,48,120.0,1,0,1,0,0,0,0
1,Shanghai Port,Singapore Port,67,COSCO,Sea,150,300,400,180,20,...,24,48,120.0,1,0,1,0,0,0,0
2,Singapore Port,Malaysia Port,34,COSCO,Sea,50,280,200,150,20,...,24,48,24.0,0,1,0,1,0,1,0
3,Malaysia Port,Singapore Port,34,COSCO,Sea,50,280,200,150,20,...,24,48,24.0,0,1,0,1,0,1,0
4,Shanghai Port,Malaysia Port,67,COSCO,Sea,300,180,400,130,20,...,24,48,96.0,0,0,1,0,0,1,0

In [5]:
data.isnull().sum()

Source                                     0
Destination                                0
Container Size                             0
Carrier                                    0
Travel Mode                                0
Fixed Freight Cost                         0
Port/Airport/Rail Handling Cost            0
Bunker/ Fuel Cost                          0
Documentation Cost                         0
Equipment Cost                             0
Warehouse Cost                             0
Transit Duty                               0
CustomClearance time (hours)               0
Port/Airport/Rail Handling time (hours)    0
Transit time (hours)                       0
Monday                                     0
Tuesday                                    0
Wednesday                                  0
Thursday                                   0
Friday                                     0
Saturday                                   0
Sunday                                     0
dtype: int64

In [6]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

data['Source'] = le.fit_transform(data['Source'])
data['Destination'] = le.fit_transform(data['Destination'])
data['Carrier'] = le.fit_transform(data['Carrier'])
data['Travel Mode'] = le.fit_transform(data['Travel Mode'])

In [7]:
data.head()

,Source,Destination,Container Size,Carrier,Travel Mode,Fixed Freight Cost,Port/Airport/Rail Handling Cost,Bunker/ Fuel Cost,Documentation Cost,Equipment Cost,...,CustomClearance time (hours),Port/Airport/Rail Handling time (hours),Transit time (hours),Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday
0,9,5,67,0,2,300,300,400,180,20,...,24,48,120.0,1,0,1,0,0,0,0
1,5,9,67,0,2,150,300,400,180,20,...,24,48,120.0,1,0,1,0,0,0,0
2,9,1,34,0,2,50,280,200,150,20,...,24,48,24.0,0,1,0,1,0,1,0
3,1,9,34,0,2,50,280,200,150,20,...,24,48,24.0,0,1,0,1,0,1,0
4,5,1,67,0,2,300,180,400,130,20,...,24,48,96.0,0,0,1,0,0,1,0

In [8]:
X = data.drop("Transit time (hours)", axis = 1)
y = data["Transit time (hours)"]

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [10]:
# print(X_train)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

#for error
y_train = y_train.values.reshape(-1, 1)
y_test = y_test.values.reshape(-1, 1)

y_train = scaler.fit_transform(y_train)
y_test = scaler.transform(y_test)

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
reg = LinearRegression()

In [14]:
reg.fit(X_train, y_train)

LinearRegression()

In [15]:
pred = reg.predict(X_test)

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, pred)

0.9953234573155667